version: "3"

######## 启动项目 #######

services:
  # 会员API
  user-api:
    build:
      context: .
      args:
        path: "/app/user/cmd/api"
    ports:
      - "10001:8080/tcp"
    expose:
      - 8080
    command: ./bin/main api -f etc/config.yaml
    networks:
      - mall-net

  # 会员RPC
  user-rpc:
    build:
      context: .
      args:
        path: "/app/user/cmd/rpc"
    ports:
      - "10002:8080/tcp"
    expose:
      - 8080
    command: ./bin/main grpc:server -f etc/config.yaml
    networks:
      - mall-net
  # 余额API
  balance-api:
    build:
      context: .
      args:
        path: "/app/balance/cmd/api"
    ports:
      - "10011:8080/tcp"
    expose:
      - 8080
    command: ./bin/main api -f etc/config.yaml
    networks:
      - mall-net
  # 余额RPC
  balance-rpc:
    build:
      context: .
      args:
        path: "/app/balance/cmd/rpc"
    ports:
      - "10012:8080/tcp"
    expose:
      - 8080
    command: ./bin/main grpc:server -f etc/config.yaml
    networks:
      - mall-net

networks:
  mall-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
