APPDEBUG: true

RPC:
  GRPCAddr: :8080

DB:
  DSN: root:root@tcp(host.docker.internal:3306)/mall_go?charset=utf8&loc=Asia%2FShanghai&parseTime=true&timeout=10s

REDIS:
  RedisAddr: 127.0.0.1
  RedisPassword:
  RedisDatabase: 0
  RedisTimeOut: 30